version: '4.2'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: rollyy
      POSTGRES_PASSWORD: 1234p!!!
      POSTGRES_DB: mynestdb
    networks:
      - freecodecamp
networks:
  freecodecamp:
